baseURL = "https://hugo.zengrong.net"
languageCode = "zh-CN"
title = "ZRONG's Blog"
theme = "maupassant"
# theme = "capsule"
# uglyurls = true

# Ignore the WARNING when build site: found no layout file for "HTML" for "section"
disableKinds = ['section']

[taxonomies]
  category = "category"
  tag = "tag"